name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}

          script: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            export PATH="$HOME/.local/bin:$PATH"
            cd ~/apps/ai-domain-checker-api
            git restore .
            git pull origin main
            source .venv/bin/activate
            uv add -r requirements.txt
            sudo systemctl restart ai-domain-checker-api
            sudo systemctl status ai-domain-checker-api --no-pager
